include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    avoid_print: error
    prefer_const_constructors: error
    require_trailing_commas: error
linter:
  rules:
    camel_case_types: true
    file_names: true
    prefer_const_constructors: true
    require_trailing_commas: true
    avoid_print: true
    use_key_in_widget_constructors: true
